export default {
  common: { refresh: '刷新', reset: '重置', search: '名称 / 编码 / 设备', all: '全部', actions: '操作', detail: '详情', cancel: '取消', save: '保存', confirm: '确认', noData: '没有符合当前条件的数据', createdAt: '创建时间', updatedAt: '更新时间', enabled: '启用', disabled: '停用', source: '来源系统', severity: '告警等级', status: '状态', device: '关联设备' },
  severity: { CRITICAL: '紧急', MAJOR: '重要', MINOR: '次要', INFO: '提示' },
  source: { HVAC: '空调', LIGHTING: '照明', PARKING: '停车', CHARGING: '充电', SOLAR: '光伏', STORAGE: '储能' },
  alarmStatus: { ACTIVE: '待处理', ACKNOWLEDGED: '已确认', SUPPRESSED: '已抑制', RECOVERED: '已恢复' },
  workStatus: { PENDING_ASSIGNMENT: '待分派', PENDING_ACCEPTANCE: '待接单', IN_PROGRESS: '处理中', PENDING_VERIFICATION: '待验收', CLOSED: '已关闭', CANCELLED: '已取消' },
  priority: { URGENT: '紧急', HIGH: '高', MEDIUM: '中', LOW: '低' },
  rules: { title: '告警规则配置', subtitle: '统一维护触发条件、等级、持续时间与通知策略', add: '新增规则', total: '规则总数', enabled: '启用规则', critical: '紧急规则', automatic: '自动转单', name: '规则名称', code: '规则编码', metric: '监测指标', condition: '触发条件', duration: '持续时间', notification: '通知渠道', autoTicket: '自动转单', edit: '编辑', dialogAdd: '新增告警规则', dialogEdit: '编辑告警规则', threshold: '阈值', unit: '单位', seconds: '秒', statusChanged: '规则状态已更新', saved: '规则已保存' },
  transfer: { title: '告警转工单', subtitle: '对活动告警进行确认、抑制和转单，避免重复处置', active: '活动告警', critical: '紧急告警', acknowledged: '已确认', converted: '已转工单', recoveredToday: '今日恢复', code: '告警编号', titleCol: '告警内容', value: '当前值 / 阈值', occurredAt: '发生时间', acknowledge: '确认', suppress: '抑制', createTicket: '转工单', convertedLabel: '已转单', actionComment: '处置说明', ticketTitle: '工单标题', assignee: '处理人', dueAt: '要求完成时间', convertedSuccess: '工单已创建', updated: '告警状态已更新' },
  tickets: { title: '工单处理中心', subtitle: '按分派、接单、处理、验收和关闭推进工单生命周期', pendingAssignment: '待分派', pendingAcceptance: '待接单', inProgress: '处理中', pendingVerification: '待验收', overdue: '已逾期', closedToday: '今日关闭', code: '工单编号', titleCol: '工单内容', priority: '优先级', assignee: '处理人', dueAt: '截止时间', timeline: '处理记录', assign: '分派', accept: '接单处理', complete: '提交验收', verify: '验收关闭', rework: '退回处理', cancelOrder: '取消工单', resolution: '处理结果', comment: '流转说明', transitionSuccess: '工单状态已更新', unassigned: '未分派' },
  statistics: { title: '历史告警统计', subtitle: '基于告警事件台账评估风险、恢复效率与转单闭环', days7: '近 7 天', days30: '近 30 天', days90: '近 90 天', total: '告警总量', active: '当前活动', critical: '紧急告警', conversionRate: '转单率', averageRecovery: '平均恢复', minutes: '分钟', trend: '告警趋势', severityDistribution: '等级分布', sourceDistribution: '来源分布', statusDistribution: '状态分布', recovered: '已恢复', converted: '已转单', ledgerDays: '{days} 天事件台账', pendingHint: '待处理与已确认', recoveredHint: '时间窗内已恢复', recoveryHint: '仅统计有恢复时间事件', conversionHint: '转单率 {rate}%', eventUnit: '单位：起', currentWindow: '当前时间窗', detailsTab: '告警明细', severityTab: '等级汇总', durationTab: '处理时长分析', assetsTab: '告警设备排名', rulesTab: '告警规则统计', keyword: '告警编号 / 内容 / 设备', allSeverity: '全部等级', allSource: '全部来源', allStatus: '全部状态', noEvents: '暂无符合条件的告警事件', occurredAt: '告警发生时间', content: '告警内容', assetAndCode: '设备名称 / 编号', linkedTicket: '关联工单', durationMinutes: '恢复时长（分钟）', noRecovered: '当前时间窗没有已恢复告警', noStatistics: '暂无统计数据', assetName: '设备名称', assetCode: '设备编码', rule: '告警规则', alarmCount: '告警数', activeCount: '当前活动', detailTitle: '告警详情', alarmCode: '告警编号', alarmAsset: '告警设备', sourceSeverity: '来源 / 等级', valueThreshold: '当前值 / 阈值', recoveredAt: '恢复时间', description: '告警说明', totalNote: '共 {count} 条（接口最多返回当前时间窗最近 500 条）', ruleNumber: '规则 #{id}', unlinkedRule: '未关联规则' },
};
