export default {
  common: { refresh: 'Refresh', reset: 'Reset', search: 'Name / code / device', all: 'All', actions: 'Actions', detail: 'Details', cancel: 'Cancel', save: 'Save', confirm: 'Confirm', noData: 'No data matches the current filters', createdAt: 'Created', updatedAt: 'Updated', enabled: 'Enabled', disabled: 'Disabled', source: 'Source', severity: 'Severity', status: 'Status', device: 'Device' },
  severity: { CRITICAL: 'Critical', MAJOR: 'Major', MINOR: 'Minor', INFO: 'Info' },
  source: { HVAC: 'HVAC', LIGHTING: 'Lighting', PARKING: 'Parking', CHARGING: 'Charging', SOLAR: 'Solar', STORAGE: 'Storage' },
  alarmStatus: { ACTIVE: 'Open', ACKNOWLEDGED: 'Acknowledged', SUPPRESSED: 'Suppressed', RECOVERED: 'Recovered' },
  workStatus: { PENDING_ASSIGNMENT: 'Pending assignment', PENDING_ACCEPTANCE: 'Pending acceptance', IN_PROGRESS: 'In progress', PENDING_VERIFICATION: 'Pending verification', CLOSED: 'Closed', CANCELLED: 'Cancelled' },
  priority: { URGENT: 'Urgent', HIGH: 'High', MEDIUM: 'Medium', LOW: 'Low' },
  rules: { title: 'Alarm Rules', subtitle: 'Manage trigger conditions, severity, duration, and notification policies', add: 'New Rule', total: 'Total rules', enabled: 'Enabled rules', critical: 'Critical rules', automatic: 'Auto ticket', name: 'Rule name', code: 'Rule code', metric: 'Metric', condition: 'Trigger', duration: 'Duration', notification: 'Notifications', autoTicket: 'Auto ticket', edit: 'Edit', dialogAdd: 'New Alarm Rule', dialogEdit: 'Edit Alarm Rule', threshold: 'Threshold', unit: 'Unit', seconds: 'seconds', statusChanged: 'Rule status updated', saved: 'Rule saved' },
  transfer: { title: 'Alarm to Work Order', subtitle: 'Acknowledge, suppress, and convert active alarms without duplicate handling', active: 'Active alarms', critical: 'Critical alarms', acknowledged: 'Acknowledged', converted: 'Converted', recoveredToday: 'Recovered today', code: 'Alarm ID', titleCol: 'Alarm', value: 'Value / threshold', occurredAt: 'Occurred', acknowledge: 'Acknowledge', suppress: 'Suppress', createTicket: 'Create ticket', convertedLabel: 'Converted', actionComment: 'Handling note', ticketTitle: 'Work order title', assignee: 'Assignee', dueAt: 'Due time', convertedSuccess: 'Work order created', updated: 'Alarm status updated' },
  tickets: { title: 'Work Order Center', subtitle: 'Advance work orders through assignment, acceptance, processing, verification, and closure', pendingAssignment: 'Pending assignment', pendingAcceptance: 'Pending acceptance', inProgress: 'In progress', pendingVerification: 'Pending verification', overdue: 'Overdue', closedToday: 'Closed today', code: 'Work order', titleCol: 'Description', priority: 'Priority', assignee: 'Assignee', dueAt: 'Due', timeline: 'Activity', assign: 'Assign', accept: 'Accept', complete: 'Submit', verify: 'Verify & close', rework: 'Return', cancelOrder: 'Cancel order', resolution: 'Resolution', comment: 'Transition note', transitionSuccess: 'Work order updated', unassigned: 'Unassigned' },
  statistics: { title: 'Alarm Statistics', subtitle: 'Evaluate risk, recovery efficiency, and work order conversion from the event ledger', days7: 'Last 7 days', days30: 'Last 30 days', days90: 'Last 90 days', total: 'Total alarms', active: 'Active', critical: 'Critical', conversionRate: 'Conversion rate', averageRecovery: 'Avg. recovery', minutes: 'min', trend: 'Alarm trend', severityDistribution: 'Severity', sourceDistribution: 'Sources', statusDistribution: 'Status', recovered: 'Recovered', converted: 'Converted', ledgerDays: '{days}-day event ledger', pendingHint: 'Open and acknowledged', recoveredHint: 'Recovered in this window', recoveryHint: 'Events with a recovery time only', conversionHint: 'Conversion rate {rate}%', eventUnit: 'Events', currentWindow: 'Current window', detailsTab: 'Alarm details', severityTab: 'Severity summary', durationTab: 'Handling duration', assetsTab: 'Alarm assets', rulesTab: 'Alarm rules', keyword: 'Alarm ID / description / device', allSeverity: 'All severities', allSource: 'All sources', allStatus: 'All statuses', noEvents: 'No alarm events match the filters', occurredAt: 'Occurred', content: 'Alarm', assetAndCode: 'Device / code', linkedTicket: 'Work order', durationMinutes: 'Recovery duration (min)', noRecovered: 'No recovered alarms in this window', noStatistics: 'No statistics', assetName: 'Device', assetCode: 'Device code', rule: 'Alarm rule', alarmCount: 'Alarms', activeCount: 'Active', detailTitle: 'Alarm details', alarmCode: 'Alarm ID', alarmAsset: 'Alarm device', sourceSeverity: 'Source / severity', valueThreshold: 'Value / threshold', recoveredAt: 'Recovered at', description: 'Description', totalNote: '{count} records (API returns up to the latest 500 events in this window)', ruleNumber: 'Rule #{id}', unlinkedRule: 'No linked rule' },
};
