<script setup lang="ts">
import {CircleCheck,Delete,Edit,Plus,Promotion,Refresh} from '@element-plus/icons-vue';
import {computed,onMounted,ref,watch} from 'vue';
import {ElMessage,ElMessageBox} from 'element-plus';
import {ApiError} from '@/core/api/contracts';
import {useAuthStore} from '@/core/auth/auth.store';
import DsDataTable from '@/design-system/components/DsDataTable.vue';
import DsEmpty from '@/design-system/components/DsEmpty.vue';
import DsListPageShell from '@/design-system/components/DsListPageShell.vue';
import DsPagination from '@/design-system/components/DsPagination.vue';
import DsTag from '@/design-system/components/DsTag.vue';
import {useListPageState} from '@/design-system/composables/useListPageState';
import {enterpriseMeteringApi,type MeteringModelVersion,type MeteringPointOption,type PhysicalEdgeInput,type PhysicalMeteringNode,type PhysicalMeteringTopology,type PhysicalNodeInput,type PhysicalNodeTypeOption} from '@/domain/iot/metering-loss';
import {enumLabel} from '@/core/i18n/enum-labels';
import EnterpriseViewSwitch from './components/EnterpriseViewSwitch.vue';
import PhysicalTopologyGraph from './components/PhysicalTopologyGraph.vue';
import './enterprise-metering.css';

const auth=useAuthStore(),loading=ref(true),saving=ref(false),ready=ref(false),activeView=ref('flow');
const viewOptions=[{value:'flow',label:'供电链路',icon:'flow' as const},{value:'list',label:'关系列表',icon:'list' as const}];
const versions=ref<MeteringModelVersion[]>([]),versionId=ref<number>(),topology=ref<PhysicalMeteringTopology>(),selected=ref<PhysicalMeteringNode>();
const nodeTypes=ref<PhysicalNodeTypeOption[]>([]),points=ref<MeteringPointOption[]>([]);
const versionDialog=ref(false),nodeDialog=ref(false),edgeDialog=ref(false),editingNodeId=ref<number>();
const versionForm=ref({name:'',effectiveFrom:localDateTime(new Date()),copyFromVersionId:undefined as number|undefined,remark:''});
const nodeForm=ref<PhysicalNodeInput>(emptyNode()),edgeForm=ref<PhysicalEdgeInput>({fromNodeId:0,toNodeId:0,connectionType:'SUPPLY',sortOrder:10,remark:''});
const rows=computed(()=>topology.value?.edges.map(edge=>({...edge,from:topology.value?.nodes.find(node=>node.id===edge.fromNodeId),to:topology.value?.nodes.find(node=>node.id===edge.toNodeId)}))||[]);
const {page,pageSize,pagedRows}=useListPageState({rows,resetDeps:()=>[versionId.value]});
const meteredCount=computed(()=>topology.value?.nodes.filter(node=>node.meteringPointId).length||0);
const currentVersion=computed(()=>versions.value.find(item=>item.id===versionId.value));
const managePermission='platform:enterprise-metering:topology:manage';
const isDraft=computed(()=>currentVersion.value?.status==='DRAFT'),canManage=computed(()=>auth.can(managePermission)),canShowManage=computed(()=>auth.canShow(managePermission));
const roleLabel=(value:string)=>enumLabel('physicalRole',value);
function localDateTime(value:Date){return new Date(value.getTime()-value.getTimezoneOffset()*60000).toISOString().slice(0,19)}
function emptyNode():PhysicalNodeInput{return{code:'',name:'',typeCode:'FEEDER',sortOrder:10,remark:''}}
function statusLabel(value?:string){return enumLabel('modelStatus',value)}
function versionDisplayName(version?:MeteringModelVersion){if(!version)return'';const match=version.name?.match(/V\d+/i);return match?`配电拓扑 ${match[0].toUpperCase()}`:'配电拓扑版本'}
function statusTone(value?:string){return value==='PUBLISHED'?'success':value==='DRAFT'?'warning':'info'}
function errorMessage(error:unknown,fallback:string){return error instanceof ApiError?error.message:fallback}
async function loadVersions(preferred?:number){versions.value=await enterpriseMeteringApi.topologyVersions();versionId.value=preferred??versionId.value??versions.value[0]?.id}
async function load(){if(!versionId.value)return;loading.value=true;try{topology.value=await enterpriseMeteringApi.physicalTopology(versionId.value);const previous=selected.value?.id;selected.value=topology.value.nodes.find(node=>node.id===previous)||topology.value.nodes[0]}catch(error){ElMessage.error(errorMessage(error,'配电拓扑加载失败'))}finally{loading.value=false}}
async function ensureOptions(){if(!nodeTypes.value.length)[nodeTypes.value,points.value]=await Promise.all([enterpriseMeteringApi.physicalNodeTypeOptions(),enterpriseMeteringApi.accountingPointOptions()])}
function openVersion(){if(!auth.canEnter(managePermission))return;const next=Math.max(0,...versions.value.map(item=>Number(item.name.match(/V(\d+)/i)?.[1]||0)))+1;versionForm.value={name:`园区配电拓扑 V${next}`,effectiveFrom:localDateTime(new Date()),copyFromVersionId:currentVersion.value?.id,remark:'从当前发布版复制，调整后校验并发布'};versionDialog.value=true}
async function createVersion(){if(!canManage.value)return;if(!versionForm.value.name.trim()){ElMessage.warning('请填写版本名称');return}saving.value=true;try{const created=await enterpriseMeteringApi.createTopologyVersion(versionForm.value);versionDialog.value=false;ready.value=false;await loadVersions(created.id);ready.value=true;await load();ElMessage.success('配电拓扑草稿已创建')}catch(error){ElMessage.error(errorMessage(error,'创建拓扑草稿失败'))}finally{saving.value=false}}
async function openCreateNode(){await ensureOptions();editingNodeId.value=undefined;nodeForm.value=emptyNode();nodeDialog.value=true}
async function openEditNode(node:PhysicalMeteringNode){await ensureOptions();editingNodeId.value=node.id;nodeForm.value={code:node.code,name:node.name,typeCode:node.typeCode,meteringPointId:node.meteringPointId,spaceNodeId:node.spaceNodeId,tenantId:node.tenantId,sortOrder:node.sortOrder,version:node.version,remark:''};nodeDialog.value=true}
async function saveNode(){if(!canManage.value)return;if(!versionId.value||!nodeForm.value.code.trim()||!nodeForm.value.name.trim()){ElMessage.warning('请填写节点编码和名称');return}saving.value=true;try{topology.value=editingNodeId.value?await enterpriseMeteringApi.updatePhysicalNode(versionId.value,editingNodeId.value,nodeForm.value):await enterpriseMeteringApi.createPhysicalNode(versionId.value,nodeForm.value);nodeDialog.value=false;selected.value=topology.value.nodes.find(item=>item.id===editingNodeId.value)||topology.value.nodes[topology.value.nodes.length-1];await loadVersions(versionId.value);ElMessage.success(editingNodeId.value?'节点已更新':'节点已新增')}catch(error){ElMessage.error(errorMessage(error,'保存物理节点失败'))}finally{saving.value=false}}
function openEdge(){if(!topology.value?.nodes.length)return;edgeForm.value={fromNodeId:selected.value?.id||topology.value.nodes[0].id,toNodeId:0,connectionType:'SUPPLY',sortOrder:(topology.value.edges.length+1)*10,remark:''};edgeDialog.value=true}
async function saveEdge(){if(!canManage.value)return;if(!versionId.value||!edgeForm.value.fromNodeId||!edgeForm.value.toNodeId){ElMessage.warning('请选择上游和下游节点');return}saving.value=true;try{topology.value=await enterpriseMeteringApi.createPhysicalEdge(versionId.value,edgeForm.value);edgeDialog.value=false;ElMessage.success('供电关系已新增')}catch(error){ElMessage.error(errorMessage(error,'新增供电关系失败'))}finally{saving.value=false}}
async function disableNode(node:PhysicalMeteringNode){if(!versionId.value)return;try{await ElMessageBox.confirm(`确定停用“${node.name}”吗？必须先移除关联供电关系。`,'停用物理节点',{type:'warning'});topology.value=await enterpriseMeteringApi.disablePhysicalNode(versionId.value,node.id,node.version);selected.value=topology.value.nodes[0];ElMessage.success('节点已停用')}catch(error){if(error!=='cancel'&&error!=='close')ElMessage.error(errorMessage(error,'停用节点失败'))}}
async function disableEdge(edge:{id:number;version:number}){if(!versionId.value)return;try{await ElMessageBox.confirm('确定移除该草稿供电关系吗？','移除关系',{type:'warning'});topology.value=await enterpriseMeteringApi.disablePhysicalEdge(versionId.value,edge.id,edge.version);ElMessage.success('关系已移除')}catch(error){if(error!=='cancel'&&error!=='close')ElMessage.error(errorMessage(error,'移除关系失败'))}}
async function validateVersion(show=true){if(!versionId.value)return false;try{const result=await enterpriseMeteringApi.validateTopologyVersion(versionId.value);if(result.valid){if(show)ElMessage.success('配电拓扑校验通过：节点均可达、无环、无重复计量点');return true}await ElMessageBox.alert(result.issues.map((item,index)=>`${index+1}. ${item}`).join('\n'),'拓扑校验未通过',{type:'warning'});return false}catch(error){ElMessage.error(errorMessage(error,'拓扑校验失败'));return false}}
async function publishVersion(){if(!versionId.value||!currentVersion.value||!await validateVersion(false))return;try{await ElMessageBox.confirm('发布后原拓扑按生效时间退役并保留历史，是否继续？','发布配电拓扑',{type:'warning'});const published=await enterpriseMeteringApi.publishTopologyVersion(versionId.value,{version:currentVersion.value.version,effectiveFrom:currentVersion.value.effectiveFrom});ready.value=false;await loadVersions(published.id);ready.value=true;await load();ElMessage.success('配电拓扑已发布')}catch(error){if(error!=='cancel'&&error!=='close')ElMessage.error(errorMessage(error,'发布拓扑失败'))}}
watch(versionId,(next,previous)=>{if(ready.value&&next&&next!==previous)load()});onMounted(async()=>{try{await loadVersions();ready.value=true;await load()}catch(error){ElMessage.error(errorMessage(error,'配电拓扑初始化失败'))}});
</script>

<template>
  <DsListPageShell title="配电拓扑" subtitle="物理电源、变压器、母线、馈线、回路和计量点的真实供电关系" page-class="enterprise-metering-page" :loading="loading">
    <template #header-extra><DsTag v-if="currentVersion" :type="statusTone(currentVersion.status)">{{ statusLabel(currentVersion.status) }} · {{ versionDisplayName(currentVersion) }}</DsTag></template>
    <div v-if="topology" class="enterprise-content">
      <section class="enterprise-query-bar">
        <div class="enterprise-query-bar__field"><label>拓扑版本</label><el-select v-model="versionId" placeholder="选择拓扑版本"><el-option v-for="item in versions" :key="item.id" :label="`${item.name}（${statusLabel(item.status)}）`" :value="item.id"/></el-select></div>
        <div class="enterprise-query-bar__summary"><span>当前口径</span><strong>{{ currentVersion?.name }}</strong><small>{{ currentVersion?.effectiveFrom?.replace('T',' ') }} 生效</small></div>
        <div class="enterprise-query-bar__actions"><el-button :icon="Refresh" @click="load">刷新</el-button><el-button v-if="canShowManage" v-permission.preview="managePermission" type="primary" :icon="Plus" @click="openVersion">新建拓扑版本</el-button></div>
      </section>
      <section class="enterprise-kpis"><article><span>物理节点</span><strong>{{ topology.nodes.length }}</strong><small>角色稳定、类型可扩展</small></article><article><span>已绑定计量点</span><strong>{{ meteredCount }}</strong><small>未绑定输配节点仍保留物理语义</small></article><article><span>供电关系</span><strong>{{ topology.edges.length }}</strong><small>有向能量流连接</small></article><article><span>拓扑校验</span><strong :class="{'enterprise-warning':topology.validationIssues.length}">{{ topology.validationIssues.length?'发现问题':'通过' }}</strong><small>{{ statusLabel(topology.version.status) }} · {{ versionDisplayName(topology.version) }}</small></article></section>
      <section class="enterprise-panel"><header class="enterprise-panel__header"><EnterpriseViewSwitch v-model="activeView" :options="viewOptions"/><div class="enterprise-validation" :class="{'has-issues':topology.validationIssues.length}">{{ topology.validationIssues.length?topology.validationIssues.join('；'):'节点均可达、无循环引用、无无效关系' }}</div></header>
        <div v-if="isDraft&&canShowManage" class="enterprise-editor-actions"><el-button v-permission="managePermission" :icon="CircleCheck" @click="validateVersion()">校验版本</el-button><el-button v-permission.preview="managePermission" :icon="Plus" @click="openCreateNode">新增节点</el-button><el-button v-permission.preview="managePermission" :icon="Plus" @click="openEdge">新增关系</el-button><el-button v-if="selected" v-permission.preview="managePermission" :icon="Edit" @click="selected&&openEditNode(selected)">编辑节点</el-button><el-button v-if="selected" v-permission="managePermission" :icon="Delete" type="danger" plain @click="selected&&disableNode(selected)">停用节点</el-button><el-button v-permission="managePermission" :icon="Promotion" type="primary" @click="publishVersion">发布版本</el-button></div>
        <div v-if="activeView==='flow'" class="enterprise-visual-layout"><div class="enterprise-visual-board"><PhysicalTopologyGraph :nodes="topology.nodes" :edges="topology.edges" :selected-id="selected?.id" @select="selected=$event"/></div><aside class="enterprise-tree-detail"><template v-if="selected"><p class="enterprise-detail-eyebrow">选中物理节点</p><h3>{{ selected.name }}</h3><dl class="enterprise-detail-list"><div><dt>节点编码</dt><dd>{{ selected.code }}</dd></div><div><dt>节点类型</dt><dd>{{ selected.typeName }}</dd></div><div><dt>固定角色</dt><dd><DsTag type="primary">{{ roleLabel(selected.role) }}</DsTag></dd></div><div><dt>计量点</dt><dd>{{ selected.meteringPointName||'未绑定' }}</dd></div><div><dt>空间</dt><dd>{{ selected.spaceName||'--' }}</dd></div><div><dt>租户</dt><dd>{{ selected.tenantName||'公共/管理方' }}</dd></div></dl><div class="enterprise-detail-callout"><strong>链路语义</strong><span>箭头方向表示真实供电方向；虚线表示备用关系，节点颜色区分固定角色。</span></div></template><DsEmpty v-else description="点击图中节点查看详情"/></aside></div>
        <section v-else class="ds-list-table-shell ds-list-table-shell--embedded enterprise-table-shell"><DsDataTable :rows="pagedRows as unknown as Record<string,unknown>[]" :columns="[]" table-layout="fixed"><el-table-column label="上游节点" min-width="210"><template #default="{row}"><div class="enterprise-primary-cell"><strong>{{ row.from?.name }}</strong><small>{{ row.from?.code }} · {{ row.from?.typeName }}</small></div></template></el-table-column><el-table-column label="下游节点" min-width="210"><template #default="{row}"><div class="enterprise-primary-cell"><strong>{{ row.to?.name }}</strong><small>{{ row.to?.code }} · {{ row.to?.typeName }}</small></div></template></el-table-column><el-table-column prop="connectionType" label="连接关系" width="120"><template #default="{row}"><DsTag type="primary">{{ enumLabel('connectionType', row.connectionType) }}</DsTag></template></el-table-column><el-table-column prop="status" label="状态" width="90"><template #default><DsTag type="success">有效</DsTag></template></el-table-column><el-table-column v-if="isDraft&&canManage" label="操作" width="90" fixed="right"><template #default="{row}"><el-button link type="danger" @click="disableEdge(row)">移除</el-button></template></el-table-column><template #empty><DsEmpty description="当前版本暂无物理供电关系"/></template></DsDataTable><footer v-if="rows.length" class="ds-list-table-footer ds-list-table-footer--pagination-only"><DsPagination v-model:page="page" v-model:page-size="pageSize" :total="rows.length"/></footer></section>
      </section>
    </div>

    <el-dialog v-model="versionDialog" title="新建配电拓扑草稿" width="620px" destroy-on-close><el-form label-position="top"><el-form-item label="版本名称" required><el-input v-model="versionForm.name"/></el-form-item><el-form-item label="计划生效时间" required><el-date-picker v-model="versionForm.effectiveFrom" type="datetime" value-format="YYYY-MM-DDTHH:mm:ss" style="width:100%"/></el-form-item><el-form-item label="复制来源"><el-select v-model="versionForm.copyFromVersionId" clearable style="width:100%"><el-option v-for="item in versions" :key="item.id" :label="`${item.name}（${statusLabel(item.status)}）`" :value="item.id"/></el-select></el-form-item><el-form-item label="说明"><el-input v-model="versionForm.remark" type="textarea" :rows="3"/></el-form-item></el-form><template #footer><el-button @click="versionDialog=false">取消</el-button><el-button v-permission="managePermission" type="primary" :loading="saving" :disabled="!canManage" @click="createVersion">创建草稿</el-button></template></el-dialog>
    <el-dialog v-model="nodeDialog" :title="editingNodeId?'编辑物理节点':'新增物理节点'" width="660px" destroy-on-close><el-form label-position="top" class="physical-form"><el-form-item label="节点编码" required><el-input v-model="nodeForm.code" :disabled="Boolean(editingNodeId)"/></el-form-item><el-form-item label="节点名称" required><el-input v-model="nodeForm.name"/></el-form-item><el-form-item label="节点类型" required><el-select v-model="nodeForm.typeCode" style="width:100%"><el-option v-for="item in nodeTypes" :key="item.code" :label="`${item.name} · ${roleLabel(item.role)}`" :value="item.code"/></el-select></el-form-item><el-form-item label="计量点"><el-select v-model="nodeForm.meteringPointId" clearable filterable style="width:100%"><el-option v-for="item in points" :key="item.id" :label="`${item.name} · ${item.code}`" :value="item.id"/></el-select></el-form-item><el-form-item label="排序"><el-input-number v-model="nodeForm.sortOrder" :min="0" :step="10"/></el-form-item><el-form-item label="说明"><el-input v-model="nodeForm.remark" type="textarea" :rows="2"/></el-form-item></el-form><template #footer><el-button @click="nodeDialog=false">取消</el-button><el-button v-permission="managePermission" type="primary" :loading="saving" :disabled="!canManage" @click="saveNode">保存节点</el-button></template></el-dialog>
    <el-dialog v-model="edgeDialog" title="新增供电关系" width="620px" destroy-on-close><el-alert type="info" :closable="false" title="连接方向必须与实际能量流一致；系统会阻止自引用、重复关系和循环供电。"/><el-form label-position="top" style="margin-top:16px"><el-form-item label="上游节点" required><el-select v-model="edgeForm.fromNodeId" filterable style="width:100%"><el-option v-for="item in topology?.nodes" :key="item.id" :label="`${item.name} · ${item.code}`" :value="item.id"/></el-select></el-form-item><el-form-item label="下游节点" required><el-select v-model="edgeForm.toNodeId" filterable style="width:100%"><el-option v-for="item in topology?.nodes" :key="item.id" :label="`${item.name} · ${item.code}`" :value="item.id"/></el-select></el-form-item><el-form-item label="连接类型"><el-select v-model="edgeForm.connectionType" style="width:100%"><el-option label="常态供电" value="SUPPLY"/><el-option label="能量转移" value="TRANSFER"/><el-option label="并联" value="PARALLEL"/><el-option label="备用供电" value="BACKUP"/></el-select></el-form-item><el-form-item label="说明"><el-input v-model="edgeForm.remark" type="textarea" :rows="2"/></el-form-item></el-form><template #footer><el-button @click="edgeDialog=false">取消</el-button><el-button v-permission="managePermission" type="primary" :loading="saving" :disabled="!canManage" @click="saveEdge">保存关系</el-button></template></el-dialog>
  </DsListPageShell>
</template>

<style scoped>
.enterprise-editor-actions{display:flex;align-items:center;gap:8px;padding:12px 16px;border-bottom:1px solid var(--el-border-color-lighter);background:var(--el-fill-color-extra-light);flex-wrap:wrap}.physical-form{display:grid;grid-template-columns:1fr 1fr;gap:0 16px}.physical-form :deep(.el-form-item:last-child){grid-column:1/-1}
@media(max-width:900px){.physical-form{grid-template-columns:1fr}.physical-form :deep(.el-form-item){grid-column:1}}
</style>
