import type { Component } from 'vue';
import {
  Bell,
  ChatDotRound,
  Connection,
  DataAnalysis,
  Files,
  HomeFilled,
  Lightning,
  List,
  Monitor,
  OfficeBuilding,
  Operation,
  PieChart,
  Setting,
  Tickets,
  User,
} from '@element-plus/icons-vue';

export const menuIconMap: Record<string, Component> = {
  abnormal: Bell,
  ai: ChatDotRound,
  alarm: Bell,
  analytics: DataAnalysis,
  area: OfficeBuilding,
  assets: OfficeBuilding,
  audit: Files,
  balance: List,
  carbon: DataAnalysis,
  charging: Lightning,
  cockpit: PieChart,
  dictionary: List,
  energy: Lightning,
  erp: Files,
  export: Files,
  gateway: Connection,
  grid: Monitor,
  home: HomeFilled,
  hvac: Operation,
  integration: Connection,
  knowledge: Files,
  link: Connection,
  lighting: Lightning,
  loss: DataAnalysis,
  menu: List,
  meter: List,
  metering: DataAnalysis,
  monitor: Monitor,
  operations: PieChart,
  organization: OfficeBuilding,
  parking: OfficeBuilding,
  permission: User,
  pv: Lightning,
  report: Files,
  rules: Setting,
  screen: Monitor,
  settings: Setting,
  settlement: Tickets,
  storage: Files,
  stream: Bell,
  tenant: User,
  ticket: Tickets,
  topology: Connection,
  user: User,
  video: Monitor,
  welcome: HomeFilled,
  water: List,
  workbench: Operation,
};
